#!/usr/bin/env bash
# a script that does all listed tasks  in 100-file
terminator()
{
	rm /var/run/myscript.pid
	exit
}
echo "$$" > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me ?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
