#!/usr/bin/env bash
# "Best School" 10 times with a loop.
#  before the last print "hi".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
