#!/usr/bin/env bash
# echos numbers from 1-20 in addition to:
#   "bad luck from Japan" in the 9th 
#   "bad luck from Italy" in the 17th 
#   "bad luck from China" in the 4th 

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
